import db_connection from '../database/db_connection.js';
import ButterfliesModel from '../models/ButterfliesModel.js';

// Array con los datos de las mariposas para popular la bbdd de prueba
const butterflies = [
  {
    "name": "Mariposa monarca",
    "order": "Lepidoptera",
    "family": "Danaidae",
    "color": "Naranja con negro",
    "size": "10 cm",
    "origin": "México",
    "location": "América del Norte",
    "habitat": "Bosques de oyamel",
    "plants": "Asclepias",
    "cycle": "Huevo, oruga, crisálida y adulto",
    "img": "https://static.nationalgeographic.es/files/styles/image_3200/public/2273.600x450.jpg?w=1600",
    "fenology": "Migración en otoño, reproducción en primavera y verano",
    "id": "3001"
  },
  {
    "id": "3002",
    "name": "Morpho azul",
    "order": "Lepidoptera",
    "family": "Nymphalidae",
    "color": "Azul metálico",
    "size": "15 cm",
    "origin": "Brasil",
    "location": "Selvas del Amazonas",
    "habitat": "Bosques tropicales",
    "plants": "Frutas fermentadas, savia de árboles",
    "cycle": "Huevo, larva, pupa y adulto",
    "img": "https://palmitospark.es/wp-content/uploads/2023/04/butterfly-g31bc30040_1280.jpg",
    "fenology": "Activa todo el año"
  },
  {
    "id": "3003",
    "name": "Heliconius charithonia",
    "order": "Lepidoptera",
    "family": "Nymphalidae",
    "color": "Negro con rayas amarillas",
    "size": "7.5 cm",
    "origin": "América Central",
    "location": "Desde México hasta Florida",
    "habitat": "Bosques húmedos y jardines",
    "plants": "Passiflora",
    "cycle": "Completo en 4 semanas",
    "img": "https://upload.wikimedia.org/wikipedia/commons/c/cf/Heliconius_charithonia%2C_Mariposario_de_Icod_de_los_Vinos%2C_Tenerife%2C_Espa%C3%B1a%2C_2012-12-13%2C_DD_04.jpg",
    "fenology": "Todo el año en climas cálidos"
  },
  {
    "name": "Agraulis vanillae",
    "order": "Lepidoptera",
    "family": "Nymphalidae",
    "color": "Anaranjado brillante con manchas negras",
    "size": "7 cm",
    "origin": "Sur de EE. UU.",
    "location": "América Central y del Sur",
    "habitat": "Zonas abiertas, jardines",
    "plants": "Passiflora",
    "cycle": "30 días",
    "img": "https://upload.wikimedia.org/wikipedia/commons/b/bc/Agraulis_vanillae_butterfly_from_above.JPG",
    "fenology": "Primavera a otoño",
    "id": "3004"
  },
  {
    "name": "Danaus gilippus",
    "order": "Lepidoptera",
    "family": "Danaidae",
    "color": "Café rojizo con bordes negros",
    "size": "9 cm",
    "origin": "América del Sur",
    "location": "Tropical y subtropical americano",
    "habitat": "Sabana y matorral",
    "plants": "Asclepias",
    "cycle": "Huevo, larva, crisálida, adulto",
    "img": "https://jardin.inecol.mx/images/MARIPOSA_MES/Danaus_gilippus_thersippus.jpg",
    "fenology": "Todo el año en zonas cálidas",
    "id": "3005"
  },
  {
    "id": "3006",
    "name": "Diaethria clymena",
    "order": "Lepidoptera",
    "family": "Nymphalidae",
    "color": "Rojo, azul y blanco, con patrón 88",
    "size": "4 cm",
    "origin": "Colombia",
    "location": "América del Sur",
    "habitat": "Bosques lluviosos bajos",
    "plants": "Frutas, savia",
    "cycle": "Larva especializada en Ulmaceae",
    "img": "https://inaturalist-open-data.s3.amazonaws.com/photos/347373297/original.jpeg",
    "fenology": "Activa todo el año"
  },
  {
    "id": "3007",
    "name": "Caligo memnon",
    "order": "Lepidoptera",
    "family": "Nymphalidae",
    "color": "Marrón con ojos grandes en las alas",
    "size": "15 cm",
    "origin": "Ecuador",
    "location": "Selvas tropicales de América del Sur",
    "habitat": "Bajo dosel forestal",
    "plants": "Plátano, Heliconia",
    "cycle": "40 a 60 días",
    "img": "https://upload.wikimedia.org/wikipedia/commons/1/10/Caligo_memnon.jpg",
    "fenology": "Todo el año"
  },
  {
    "id": "3009",
    "name": "Phoebis sennae",
    "order": "Lepidoptera",
    "family": "Pieridae",
    "color": "Amarillo brillante",
    "size": "7 cm",
    "origin": "América Latina",
    "location": "Desde EE. UU. hasta Argentina",
    "habitat": "Campos abiertos y bordes de bosque",
    "plants": "Senna, Cassia",
    "cycle": "3 semanas",
    "img": "https://inaturalist-open-data.s3.amazonaws.com/photos/158767272/original.jpg",
    "fenology": "Primavera a otoño"
  },
  {
    "name": "Anartia fatima",
    "order": "Lepidoptera",
    "family": "Nymphalidae",
    "color": "Marrón con blanco y naranja",
    "size": "6.5 cm",
    "origin": "Centroamérica",
    "location": "Desde Texas hasta Panamá",
    "habitat": "Zonas húmedas y abiertas",
    "plants": "Lantana, Bidens pilosa",
    "cycle": "20 a 30 días",
    "img": "https://upload.wikimedia.org/wikipedia/commons/f/fa/Banded_Peacock.jpg",
    "fenology": "Todo el año en zonas tropicales",
    "id": "3010"
  },
  {
    "id": "3011",
    "name": "Junonia evarete",
    "order": "Lepidoptera",
    "family": "Nymphalidae",
    "color": "Naranja con círculos ocelados negros",
    "size": "6 cm",
    "origin": "América del Sur",
    "location": "Desde Brasil hasta México",
    "habitat": "Praderas abiertas",
    "plants": "Ruellia, Justicia",
    "cycle": "28 días",
    "img": "https://inaturalist-open-data.s3.amazonaws.com/photos/194136689/original.jpeg",
    "fenology": "Primavera y verano"
  },
  {
    "id": "3012",
    "name": "Hamadryas februa",
    "order": "Lepidoptera",
    "family": "Nymphalidae",
    "color": "Gris con patrones azulados",
    "size": "7 cm",
    "origin": "Sudamérica",
    "location": "Selvas tropicales",
    "habitat": "Bosques secos y húmedos",
    "plants": "Frutas maduras",
    "cycle": "35 días",
    "img": "https://pictureinsect.com/wiki-image/1080/153826633160065048.jpeg",
    "fenology": "Todo el año"
  },
  {
    "id": "3013",
    "name": "Siproeta stelenes",
    "order": "Lepidoptera",
    "family": "Nymphalidae",
    "color": "Verde lima con bordes marrones",
    "size": "7.5 cm",
    "origin": "Centroamérica",
    "location": "América Central y del Sur",
    "habitat": "Bosques tropicales y jardines",
    "plants": "Ruellia, Lantana",
    "cycle": "30 a 40 días",
    "img": "https://upload.wikimedia.org/wikipedia/commons/c/c4/Malachite_%28Siproeta_stelenes%29_dorsal_%281%29.jpg",
    "fenology": "Primavera a otoño"
  },
  {
    "name": "Adelpha fessonia",
    "order": "Lepidoptera",
    "family": "Nymphalidae",
    "color": "Negro con bandas naranjas y blancas",
    "size": "6 cm",
    "origin": "México",
    "location": "Texas, México y Centroamérica",
    "habitat": "Bosques subtropicales",
    "plants": "Celtis, Lantana",
    "cycle": "3 semanas",
    "img": "https://www.butterfliesandmoths.org/sites/default/files/bamona_images/adelpha-fessonia-jen-sanders-1_1.jpg",
    "fenology": "Verano y otoño",
    "id": "3014"
  },
  {
    "id": "3015",
    "name": "Papilio garamas",
    "order": "Lepidoptera",
    "family": "Papilionidae",
    "color": "Negro con amarillo intenso",
    "size": "11 cm",
    "origin": "América Central",
    "location": "Bosques de montaña",
    "habitat": "Bosques nubosos y templados",
    "plants": "Rutaceae",
    "cycle": "35 días",
    "img": "https://pictureinsect.com/wiki-image/1080/153936691697025028.jpeg",
    "fenology": "Mayo a noviembre"
  },
  {
    "id": "3016",
    "name": "Eurytides marcellus",
    "order": "Lepidoptera",
    "family": "Papilionidae",
    "color": "Blanco con rayas negras y colas largas",
    "size": "8 cm",
    "origin": "EE. UU.",
    "location": "Sur de EE. UU. y México",
    "habitat": "Campos abiertos y bosques",
    "plants": "Asimina",
    "cycle": "25 días",
    "img": "https://lh4.googleusercontent.com/proxy/f_sjmAeVv0J3HybvXk5rlpWQstza03-2zyeeOJIRx-OwOXaaItkkC1byAsvaBa-nwMq4omncDZAhv184LlneurUPeCc_kx_B7uewPE3IrlXhtbJzZknM1g",
    "fenology": "Primavera a otoño"
  },
  {
    "id": "3017",
    "name": "Battus polydamas",
    "order": "Lepidoptera",
    "family": "Papilionidae",
    "color": "Negro con manchas verdes o amarillas",
    "size": "10 cm",
    "origin": "Caribe",
    "location": "América tropical",
    "habitat": "Zonas abiertas tropicales",
    "plants": "Aristolochia",
    "cycle": "4 semanas",
    "img": "https://inaturalist-open-data.s3.amazonaws.com/photos/987966/original.jpg",
    "fenology": "Todo el año"
  },
  {
    "id": "3018",
    "name": "Marpesia petreus",
    "order": "Lepidoptera",
    "family": "Nymphalidae",
    "color": "Naranja con patrón marrón",
    "size": "7 cm",
    "origin": "América Central",
    "location": "Desde Texas hasta Perú",
    "habitat": "Bosques y claros",
    "plants": "Croton, Frutas",
    "cycle": "3 a 5 semanas",
    "img": "https://jardin.inecol.mx/images/MARIPOSA_MES/alas_daga.jpg",
    "fenology": "Todo el año en clima cálido"
  },
  {
    "id": "3019",
    "name": "Hypanartia lethe",
    "order": "Lepidoptera",
    "family": "Nymphalidae",
    "color": "Anaranjado y negro con líneas finas",
    "size": "6.5 cm",
    "origin": "Sudamérica",
    "location": "Andes y Amazonía",
    "habitat": "Bosques de niebla",
    "plants": "Ortiga, Urticaceae",
    "cycle": "30 días",
    "img": "https://inaturalist-open-data.s3.amazonaws.com/photos/1070139/original.jpg",
    "fenology": "Todo el año"
  },
  {
    "id": "3020",
    "name": "Mechanitis polymnia",
    "order": "Lepidoptera",
    "family": "Nymphalidae",
    "color": "Naranja translúcido con bordes negros",
    "size": "6 cm",
    "origin": "Amazonas",
    "location": "América del Sur",
    "habitat": "Bosques húmedos bajos",
    "plants": "Solanaceae",
    "cycle": "35 días",
    "img": "https://upload.wikimedia.org/wikipedia/commons/f/f3/Disturbed_Tigerwings%2C_Quito.jpg",
    "fenology": "Todo el año"
  },
  {
    "name": "Actinote thalia",
    "order": "Lepidoptera",
    "family": "Nymphalidae",
    "color": "Negro con marcas naranjas",
    "size": "5.5 cm",
    "origin": "Brasil",
    "location": "Amazonía y Mata Atlántica",
    "habitat": "Bosques húmedos",
    "plants": "Asteraceae",
    "cycle": "28 días",
    "img": "https://www.ecoregistros.org/site/images/albumes/246/10145/Nymphalidae--Actinote-pyrrha--Perezosa-Grande.jpg",
    "fenology": "Primavera y verano",
    "id": "3021"
  },
  {
    "id": "3022",
    "name": "Catonephele numilia",
    "order": "Lepidoptera",
    "family": "Nymphalidae",
    "color": "Negro con puntos anaranjados (machos)",
    "size": "6.5 cm",
    "origin": "América tropical",
    "location": "Centro y Sudamérica",
    "habitat": "Selvas y zonas húmedas",
    "plants": "Frutas fermentadas",
    "cycle": "30 días",
    "img": "https://inaturalist-open-data.s3.amazonaws.com/photos/43089762/large.jpg",
    "fenology": "Todo el año"
  },
  {
    "id": "3023",
    "name": "Hemiargus ceraunus",
    "order": "Lepidoptera",
    "family": "Lycaenidae",
    "color": "Azul claro (machos), marrón (hembras)",
    "size": "2.5 cm",
    "origin": "América del Norte",
    "location": "Sur de EE. UU. y Caribe",
    "habitat": "Áreas abiertas y campos",
    "plants": "Fabaceae",
    "cycle": "2 semanas",
    "img": "https://upload.wikimedia.org/wikipedia/commons/b/b4/Ceraunus_Blue_%285076094341%29.jpg",
    "fenology": "Primavera a otoño"
  },
  {
    "name": "Eumaeus atala",
    "order": "Lepidoptera",
    "family": "Lycaenidae",
    "color": "Negro con manchas azules y rojas",
    "size": "4.5 cm",
    "origin": "Florida",
    "location": "EE. UU., Bahamas y Caribe",
    "habitat": "Áreas costeras",
    "plants": "Zamia (cícadas)",
    "cycle": "3 semanas",
    "img": "https://www.flawildflowers.org/wp-content/uploads/2021/06/Eumaeus-atala-Keim-banner.jpg",
    "fenology": "Todo el año en zonas cálidas",
    "id": "3024"
  },
  {
    "id": "3025",
    "name": "Pyrisitia lisa",
    "order": "Lepidoptera",
    "family": "Pieridae",
    "color": "Amarillo pálido",
    "size": "3.5 cm",
    "origin": "América Central",
    "location": "Desde EE. UU. hasta Panamá",
    "habitat": "Zonas abiertas",
    "plants": "Leguminosas",
    "cycle": "2 a 3 semanas",
    "img": "https://inaturalist-open-data.s3.amazonaws.com/photos/250850/large.jpg",
    "fenology": "Verano y otoño"
  },
  {
    "id": "3026",
    "name": "Anteos maerula",
    "order": "Lepidoptera",
    "family": "Pieridae",
    "color": "Amarillo intenso con alas grandes",
    "size": "11 cm",
    "origin": "Sudamérica",
    "location": "Desde Argentina hasta México",
    "habitat": "Zonas tropicales",
    "plants": "Cassia, Senna",
    "cycle": "1 mes",
    "img": "https://static.inaturalist.org/photos/2618368/large.JPG",
    "fenology": "Todo el año"
  },
  {
    "id": "3027",
    "name": "Panacea prola",
    "order": "Lepidoptera",
    "family": "Nymphalidae",
    "color": "Rojo anaranjado con azul metálico",
    "size": "8.5 cm",
    "origin": "Colombia",
    "location": "Andes y piedemontes",
    "habitat": "Bosques nublados",
    "plants": "Jugos de frutas, savia",
    "cycle": "35 días",
    "img": "https://pictureinsect.com/wiki-image/1080/154003452668674064.jpeg",
    "fenology": "Invierno y primavera"
  },
  {
    "id": "3028",
    "name": "Opsiphanes cassina",
    "order": "Lepidoptera",
    "family": "Nymphalidae",
    "color": "Marrón con ojos falsos en las alas",
    "size": "9 cm",
    "origin": "Amazonas",
    "location": "Centro y Sudamérica",
    "habitat": "Bosques densos",
    "plants": "Platanus, Palmae",
    "cycle": "40 días",
    "img": "https://upload.wikimedia.org/wikipedia/commons/9/99/Nymphalidae_-_Opsiphanes_cassina.JPG",
    "fenology": "Todo el año"
  },
  {
    "name": "Zaretis itys",
    "order": "Lepidoptera",
    "family": "Nymphalidae",
    "color": "Imita hojas secas (mimetismo)",
    "size": "7.5 cm",
    "origin": "Brasil",
    "location": "América del Sur",
    "habitat": "Bosques secos tropicales",
    "plants": "Frutas caídas",
    "cycle": "30 días",
    "img": "https://inaturalist-open-data.s3.amazonaws.com/photos/24713160/large.jpeg",
    "fenology": "Estacional",
    "id": "3029"
  },
  {
    "id": "3030",
    "name": "Hamadryas feronia",
    "order": "Lepidoptera",
    "family": "Nymphalidae",
    "color": "Gris moteado con azul",
    "size": "7.5 cm",
    "origin": "América Central",
    "location": "Centro y norte de Sudamérica",
    "habitat": "Bosques secos y húmedos",
    "plants": "Frutas fermentadas",
    "cycle": "1 mes",
    "img": "https://inaturalist-open-data.s3.amazonaws.com/photos/15559975/large.jpg",
    "fenology": "Todo el año"
  }
];

const seedDatabase = async () => {
  try {
    // Autenticar la conexión
    await db_connection.authenticate();
    console.log('Conexión establecida correctamente.');

    // Sincronizar el modelo (asegura que la tabla exista)
    await ButterfliesModel.sync({ force: true }); // force: true BORRA la tabla y la vuelve a crear
    console.log('Tabla de mariposas sincronizada.');

    // Insertar los datos en la tabla
    await ButterfliesModel.bulkCreate(butterflies);
    console.log('🦋 Datos de mariposas insertados correctamente!');

  } catch (error) {
    console.error('Error al poblar la base de datos:', error);
  } finally {
    // Cierra la conexión
    await db_connection.close();
    console.log('Conexión cerrada.');
  }
};

// Ejecuta la función
seedDatabase();